---
- name: Setup Analytics Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    ansible_python_interpreter: auto_silent
  roles:
    - role: essentials
    - role: user
    - role: nginx
    - role: agent
    - role: node_exporter
    - role: filebeat
    - role: docker
    - role: plausible
