---
- name: Change Root Password
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    ansible_python_interpreter: auto_silent
  roles:
    - role: mariadb_change_root_password
    - role: mysqld_exporter
    - role: deadlock_logger
