---
- name: Change Root Password on Secondary
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    ansible_python_interpreter: auto_silent
  roles:
    - role: mariadb_change_root_password_secondary
    - role: mysqld_exporter
