---
- name: Check if package is installed
  hosts: all
  become_user: root
  become_method: sudo
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Check if package is installed
      debug:
        var: ansible_facts.packages
      failed_when: '"{{ pkg }}" not in ansible_facts.packages'
