---
- name: Setup ProxySQL
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    ansible_python_interpreter: auto_silent
  roles:
    - role: docker
    - role: proxysql
    - role: proxysql_monitor
