---
- name: Setup Server Exporters
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    ansible_python_interpreter: auto_silent
  roles:
    - role: node_exporter
    - role: cadvisor
    - role: statsd_exporter
    - role: monitoring_password
